apiVersion: 1

datasources:
  - name: InfluxDB
    uid: influxdb
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true

    jsonData:
      version: Flux
      organization: super-bumba
      defaultBucket: sensors

    secureJsonData:
      token: $INFLUX_TOKEN